### ISSUE TITLE
Discuss: application.yml 환경별 분리

### ISSUE THREAD

**Issue by seonpilKim** [GraduationWorkSalesProject/Spring-GraduationWorkSalesProject#14]
### 현 상황
- application.yml에 존재하는 민감정보들이 모두 공개되어 있고, 몇몇 설정들도 실제 배포시에는 수정해야 함.
### application.yml을 환경별로 분리해서 관리
![image](https://user-images.githubusercontent.com/68049320/138444103-6e0f1b18-b2e3-40af-8348-c3959f7594ec.png)
- `application-dev.yml`: 개발 환경(local)
- `application-test.yml`: 테스트 환경(heroku)
- `application-prod.yml`: 운영 환경(aws)
> yml 파일은 노션을 이용해서 공유하면 좋을 것 같습니다!
### gitignore에 추가
```gradle
src/main/resources/application.yml
src/main/resources-dev/application-dev.yml
src/main/resources-test/application-test.yml
src/main/resources-prod/application-prod.yml
```
### 빌드 시, buid.gradle에서 환경 설정 추가
![image](https://user-images.githubusercontent.com/68049320/138444465-2036c9d5-8c2b-404e-acb4-d81bf48eae15.png)
> 참고 포스팅: https://emgc.tistory.com/130

_Originally posted by @seonpilKim in https://github.com/GraduationWorkSalesProject/Spring-GraduationWorkSalesProject/issues/9#issuecomment-947640269_

**Comment by NohYeaJin** [comment]
정리 정말 감사합니다 확인했고 노션에 추가했습니다!
