### ISSUE TITLE
img 관련 논의

### ISSUE THREAD

**Issue by NohYeaJin** [GraduationWorkSalesProject/Spring-GraduationWorkSalesProject#17]
예전에 선필님이 올리신 코드에서 주석으로 img 관련해서 논의 필요하다고 적어주셨던 것 같은데 
상품 부분은 상품 올릴때 사진까지 등록을 해야해서 슬슬 정해야 할 것 같습니다 (아니면 정해진게 있나요?)

1. 이미지 타입을 하나로 통일할지
2. db 이미지 컬럼 그대로 그냥 넣으면 될지
3. 그 외에 설정해야할 부분이 있을지  

의견 부탁드립니다!

**Comment by seonpilKim** [comment]
1. 음 다른 사이트들은 이미지 파일 업로드할 때, 어떻게 하나 찾아보니까 거의 다 제한이 딱히 없는 것 같더라구요.
그래서 찾아봤는데, `image/gif`, `image/png`, `image/jpeg`, `image/bmp`, `image/webp` 이 정도 추가하면 될 것 같아요!
    > MIME type 확인 방법: https://offbyone.tistory.com/330
    > MIME type이란?: https://zzandoli.tistory.com/60
2. 이미지 자체를 db에 넣는다는 말씀이신가요?
저희 ERD 설계할 땐 uuid, name, type별로 나누어서 저장했던 것 같아요!
3. 일단 저희 파일 서버가 따로 없어서, 임시로 구글 클라우드에 기본 이미지 아무거나 저장해놓고, 그 url을 저장소로 사용하는건 어떨까요?
