### ISSUE TITLE
Discuss: DTO 사용 규칙에 관한 의견

### ISSUE THREAD

**Issue by seonpilKim** [GraduationWorkSalesProject/Spring-GraduationWorkSalesProject#8]
# DTO 사용 목적
⚠**아래는 제 의견입니다! 다른 분들 의견도 comment에 남겨주시면 감사하겠습니다!**
### @RequestBody
- JSON을 parsing하는 `MappingJackson2HttpMessageConverter`가 `ObjectMapper`를 이용하여 JSON을 Java 객체로 역직렬화하기 때문에, 기본 생성자와 Getter가 필수
  - access를  protected까지 지원해주므로, 가능한 외부에서 호출하지 못하도록 protected로 설정
  - [참고 포스팅](https://velog.io/@conatuseus/RequestBody%EC%97%90-%EC%99%9C-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%84%B1%EC%9E%90%EB%8A%94-%ED%95%84%EC%9A%94%ED%95%98%EA%B3%A0-Setter%EB%8A%94-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-3-idnrafiw) 
- 값을 서버에서 검증하는 로직 필요
    > **사용**: `Bean Validation`, `@NoArgsConstructor(access = AccessLevel.PROTECTED)`, `@Getter`
### @ModelAttribute & @RequestParam
- Http body 혹은 Query string을 Java 객체에 바인딩하는 형태 -> 생성자 or Setter으로 바인딩 가능
  - 불변을 위해 Setter 대신 생성자 방식 사용
- 값을 서버에서 검증하는 로직 필요
    > **사용**: `Bean Validation`, `@AllArgsConstructor`, `@Getter`
## Response 목적
- 검증이 따로 필요 없음 -> Setter대신 생성자 방식 사용, (자바 객체 -> JSON) parsing 위해 Getter 추가
    >  **사용**: `@AllArgsConstructor`, `@Getter`
___
추가로, Controller에서 각 메소드별로
@xxxMapping(value = "/aaa", consumes = MediaType.APPLICATION_JSON_VALUE)
@xxxMapping(value = "/aaa", consumes = APPLICATION_FORM_URLENCODED_VALUE)
위와 같이 Content-Type도 명시해놓으면 더 좋을 것 같은데, 의견 부탁드립니다!
  1. Form인 경우, Swagger 연동했을 때 consumes 설정을 추가해줘야 type이 올바르게 적용되더라구요!
       - (Swagger 관련 정리 노션 링크: [바로가기](https://lilac-freeze-4ae.notion.site/Swagger-588c4a1f00044eda80491a28459ccae6))
  2. 프론트에서 정해진 요청 타입으로만 데이터를 전달하도록 제한하는 의도 포함

p.s) Response는 거의 JSON일테니 produces는 굳이 사용 안 해도 될 것 같습니다.

**Comment by seonpilKim** [comment]
DTO에는 setter가 있어도 딱히 상관 없어서 보통 `@Data`  `@AllArgsConstructor`, `@NoArgsConstructors` 세 개 다 넣고 사용해도 문제 없다고는 합니다!
  > p.s) (현 배민 팀장) 김영한님도 DTO에는 그냥 `@Data` 사용하신다고 합니다

Request랑 Response 구분은 `Validation`이 있냐 없냐로만 구분해도 충분할 것 같기도 해요!
다른 분들 의견은 어떠신가요??

**Comment by NohYeaJin** [comment]
DTO에 대해서 이렇게 자세하게 생각해본적은 없는데 정리해주셔서 정말 감사합니다!
DTO관련 내용에서는 대부분 동의하고, 모르는 부분은 배워서 구현할 수 있을 것 같습니다
근데 저는 DTO 클래스를 이렇게 명확하게 구분한 것이 처음이라 순수하게 궁금한점이 있는데 , 원래 DTO가 이렇게 많이 생기는지, 모든 요청 응답마다 만드는 형태인지 궁금합니다...!! (검색해보니 개발자들마다 좀 다르고, inner class로 만들어서 하는 사람도 있고 모든 DTO를 다 만들어두는 사람도 있는 것 같아서 혹시 선필님의 프로젝트 경험에서 나온 DTO구조인지, 아니면 따로 이 부분에 대해서 배우신 거라면 어떻게 배우시고 기준을 정하셨는지 궁금합니다)
controller 부분 consume은 보기만 했는데 사용은 처음 해볼 것 같습니다 공부해서 구현할 때 추가하도록 하겠습니다!

**Comment by seonpilKim** [comment]
### 모든 요청, 응답마다 DTO를 만들어야 할까?
- 요청의 경우, parameter가 1~2개 정도면 `@RequestParam`으로 받아도 될 것 같은데, 그 이상이라면 의미있는 이름의 DTO로 만드는 게 가독성도 좋고 유지보수하기 편할 것 같습니다
  > 근데 제가 테스트할 때는 `@RequestParam`에서 `@Validated`가 제대로 작동을 안하는 것 같았어요..! 
  그래서 parameter가 1개라도 DTO로 만들어서 사용하고 있는데, 혹시 해결 방법 아시면 공유 부탁드립니다..!
- 응답의 경우, 아래와 같이 Response에서 data에 응답할 데이터를 넣어서 반환하게 되는데,
- ![image](https://user-images.githubusercontent.com/68049320/137623322-6d9d682b-ca58-4860-8e2a-1f564970f71a.png)
  - expirationDateTime, certificationCode와 같이 **key**와 함께 **value**를 전달하기 위해선 **DTO**가 필요한 것 같더라구요!
![image](https://user-images.githubusercontent.com/68049320/137623262-b07ed141-0566-4952-89c4-4f914e7b0bd8.png)
- 만약, DTO로 묶지 않고 응답하게 되면
![image](https://user-images.githubusercontent.com/68049320/137623522-80fc5129-b827-4bbc-b990-61745859784d.png)
   - 아래와 같이 **value**만 전달되더라구요 
![image](https://user-images.githubusercontent.com/68049320/137623541-fedc95a9-dfb8-47e9-9714-bdc09a6d022d.png)

**그래서 저는 응답할 때는 DTO가 필수인 것 같다고 생각합니다!**
___
### DTO -> 패키징 or Inner class
이 부분은 프로젝트 규모나 개발자의 스타일에 따라 다른 것 같아요!
- 여러 메소드에서 **공통**으로 사용되는 DTO는 dto패키지에 추가
- **하나**의 메소드에서만 사용되는 DTO는 inner class로 추가 or dto패키지에 추가
  > 이 부분은 **개발자 스타일**에 따라 다른 것 같아요!
dto패키지에 추가하는 것이 깔끔하다고 생각하는 사람도 있고, 
다른 곳에서 사용되지 않는 DTO는 inner class로 추가해도 된다고 생각하는 사람도 있는 것 같습니다
**규모가 작은** 프로젝트에서는 inner class로 추가해도 유지보수에 크게 문제가 되지 않을 것 같기도 합니다
  > - **저는 그래도 최대한 역할과 책임을 분리하는게 좋다고 생각해서, 웬만해서는 dto 패키지에 추가하는 편입니다!**
___
> p.s) 저는 대부분 영한님 강의에서 배운 개념과 실무 팁, 다른 사람들의 질문과 답변등을 참고해서 기준을 정해보고 있어요!
프로젝트 경험이 적다보니, 이렇게 하는게 맞는지 확신이 안드네요.. ㅎㅎ 프로젝트 진행하면서 이런 사소한 부분들도 함께 논의하면서 기준을 정해가면 좋을 것 같습니다!

**Comment by NohYeaJin** [comment]
아...! 저도 프로젝트 경험이 많은 편이 아닌데 선필님 코드나 개념 아시는 것들이 먼가 많은 경험에서 나온 것 같아서 실무에서는 그렇게 하는건지 궁금해서 여쭤봤습니다! 적어주신 부분들 더 연구해서 공부해봐야겠네요...!! 일단 저는 이견은 없어서 써있는대로 최대한 구현해보고 pull request 올려보겠습니다!

**Comment by seonpilKim** [comment]
넵 알겠습니다!

**Comment by YOONSUNGHYEON** [comment]
저도 dto에 대해서잘 모르는데 response 같은 경우도 dto로 만든다고 하더라구용
